version: "3.7"

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgresql_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  foodgram_backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  foodgram_frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    restart: always
    volumes:
      - frontend_volume:/app/result_build/build/
    depends_on:
      - "foodgram_backend"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - "backend"
      - "frontend"

volumes:
  postgresql_volume:
  static_volume:
  media_volume:
  frontend_volume:
