version: "3.7"

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: viktoriakosh/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  frontend:
    image: viktoriakosh/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/api/docs/
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  postgresql_volume:
  static_volume:
  media_volume:
  frontend_volume:
